apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.mysql.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: {{ .Chart.Name }}
      port: {{ .Values.mysql.port }}
  clusterIP: {{ .Values.mysql.service.clusterIP }}
